version: 0.0
os: linux
files:
  - source: main
    destination: /tmp
# hooks:
#   BeforeInstall:
#     - location: scripts/deploy.sh
#       runas: root

#   AfterInstall:
#     - location: scripts/chmod.sh
#       runas: root

#   ApplicationStart:
#     - location: scripts/start.sh
#       runas: root
