version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23
  build:
    commands:
      - go mod tidy
      - GOOS=linux GOARCH=amd64 go build -o main .
artifacts:
  files:
    - main
  base-directory: $CODEBUILD_SRC_DIR
  discard-paths: no
